name: Windows C++ CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install CMake
      run: choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System' -y

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        cmake --build . --config Debug --target ALL_BUILD

    - name: Run tests with verbose output
      run: |
        cd build
        ctest --output-on-failure --verbose

    - name: Verify main executable
      run: |
        if (Test-Path "build/Debug/hftbacktest.exe") {
          echo "✓ Success: hftbacktest.exe created"
          echo "File size: $((Get-Item 'build/Debug/hftbacktest.exe').Length) bytes"
        } else {
          echo "✗ Error: hftbacktest.exe not found in build/Debug/"
          echo "Available files in build/Debug/:"
          Get-ChildItem "build/Debug/" -Name
          exit 1
        }

    - name: List test executables
      run: |
        echo "Test executables found:"
        Get-ChildItem "build/Debug/" -Filter "test_*.exe" -Name
